### ISSUE TITLE
repo not up-to-date?

### ISSUE THREAD

**Issue by wdcurry** [GPBDigital/RoundCoachMark#2]
The demo has tapPlay() whereas the repo does not. Is an update in order?

**Comment by Choock** [comment]
Oh, really? Will update asap! Thank you for the notice.

**Comment by Choock** [comment]
Should be all right by now. Please, do 'pod update'

**Comment by wdcurry** [comment]
thank you! A little tip (at least something i do: i prefer the # out the repo to update, do a "pod install" to wipe it, then uncomment the pod, and pod install again. This leaves the rest of the pods alone. Helps with projects that require stability of each repo's instance. 

Doing this now, and will look into my requirements. I am having trouble mark'ing the AIFlatSwitch control that is central to my onboarding. This one is the one on the navbar that started my issue creation. The buttons draws its specialized checkmark and i think that is somehow getting lost with the onboard sequence, so it is blank.

**Comment by wdcurry** [comment]
Do you need to do anything else to flag master as up-to-date? I have install'd a few times and still don't see tapPlay in my local machine.

**Comment by Choock** [comment]
Nope. Try 'pod update' You have to do it anyway from time to time, right? Maybe it's a good reason to do it now.

**Comment by wdcurry** [comment]
Sorry for the delay.. as mentioned, i try to not do an mass update as it impacts every repo, but will consider it if today's efforts don't pull the current bits. I like your effort that much ;) .. Just a minor fyi though, my typical technique here has not failed before, in grabbing latest bits .. cheers!

**Comment by nikolay-kapustin** [comment]
anyway, for that technique of updating pods, u can get the better via option to connect pods to any branch or tag via 
`pod 'podname', :branch => 'master' #:tag => '0.0.2' `

**Comment by Choock** [comment]
Sure, Drew, it's still possible that the problem is on our side :( but so far we don't see it. We use the pod in our ongoing project and it works ok.

**Comment by wdcurry** [comment]
I will test the above shortly. Just a note though, with only two branches, and tapPlay showing here in master, and my pod 'RoundCoachMark' not pulling it, something is amiss. I wiped the repo from my app, restarted, reset, to no avail. I can try the above noted pull augmentation, but it should not be required, all things being equal ;) ..

**Comment by wdcurry** [comment]
This grabs the latest version.. 

`pod 'RoundCoachMark', :git => 'https://github.com/GPBDigital/RoundCoachMark.git', :branch => 'master'`

edit: and i have no clue as to why the basic command wasn't pulling it. Perhaps somehow my dev box was caching it somehow (something i have not yet experienced knowingly)..
