### ISSUE TITLE
How to display RoundedCoachMark on Tabbar Item

### ISSUE THREAD

**Issue by vnanaware** [GPBDigital/RoundCoachMark#5]

**Comment by vnanaware** [comment]
I want to display this hint animation on UITabbar item. How can I achive this. thanks in advance

**Comment by nikolay-kapustin** [comment]
Unfortunately you can't. Because tabBarItem not have any api to get their view.

**Comment by vnanaware** [comment]
Okay 
thanks for response

**Comment by nikolay-kapustin** [comment]
You can add some [tricky](https://stackoverflow.com/questions/34051646/how-can-i-find-the-uiview-for-a-specific-uitabbaritem) to recognize view of bar item. I hope it helps.
